language: php
php:
  - '5.5'
  - '5.6'

script:
  - php phpunit.phar -v -c phpunit.xml

branches:
    only:
      - master

before_script:
  - phpenv config-rm xdebug.ini
  - wget https://phar.phpunit.de/phpunit.phar
  - composer install -o